### ISSUE TITLE
How to patch

### ISSUE THREAD

**Issue by OnlyNara** [sl4v3k/Shapr3d_crack#1]
How can i patch it?
I don't know how to make it

**Comment by shivam8008** [comment]
Same here,
How to patch it?
I also don't know how to make it

**Comment by sl4v3k** [comment]
this is very easy:
1. Shapr3d.exe executable in hex editor
2. navigate to address 00000001815CEDAB
3. change E8 30 31 B9 FF to 48 8B C1 90 90
4. done

**Comment by stelikas88** [comment]
hello sorry for the question but can you simple explain how to open and change the andress {what program}becuse i open with online hex editor an dont find the andress
