### ISSUE TITLE
new version 5.540.6360.0 #d1ffdcfa

### ISSUE THREAD

**Issue by adassss-jpg** [sl4v3k/Shapr3d_crack#17]
Hi sl4v3k I really appreciate your work you doing amazing job. I have a question is there any option to make new patcher for that version? Becasue I forgot to disable auto update and my last patcher stop working. :<

**Comment by sl4v3k** [comment]
Have a fun!

**Comment by adassss-jpg** [comment]
Thank you it works  :D
