### ISSUE TITLE
release for .ipa version?

### ISSUE THREAD

**Issue by crbncl** [sl4v3k/Shapr3d_crack#22]
Would it be possible for you to release a crack for the .ipa version?

I have the decrypted file and have tried decompiling it, but I haven't had any success with it.

**Comment by sl4v3k** [comment]
what is .ipa version?

**Comment by crbncl** [comment]
its version 5.601.0

**Comment by crbncl** [comment]
oh, .ipa is the container that is used for iOS that holds all the files that are in the application (basically a renamed .zip file).

inside it, i can access the executable file equivalent for iOS and decompile it.

however, because it is compiled differently to the windows version, i have trouble finding the line of code for the patch.

would you be able to decompile it if i provided the file ?

**Comment by sl4v3k** [comment]
send me please the library (.so i assume), will try to check by static analysis first, it does not work, than i will need running environment to proceed dynamic tests

**Comment by crbncl** [comment]
here is a link to the unpacked files. 
the file is just called "Shapr3D"

https://drive.google.com/drive/folders/13UKh_XO34XPGdo1i2JP1s8jIhFu602jF?usp=sharing

**Comment by crbncl** [comment]
correct, apple requires it to be compiled this way in order for it to be used in their native app store.

but I was wondering if it was possible to look at the main file (and the framework files as well) to see if you think it was still possible?

**Comment by sl4v3k** [comment]
yes difinatelly is possible, but there is no similarities to x64 Release, the function needs to be find from scratch, unfrtunatelly i do not have mac based running environment, can not proceed dynamic tests

**Comment by sl4v3k** [comment]
is there standalonen installation version of shapr3d exists for MAC? or just this boundle?

**Comment by crbncl** [comment]
there is a mac installer (.dmg) that can be downloaded directly off their [site](https://www.shapr3d.com/download/mac)

I havent had a look at that yet though.

**Comment by sl4v3k** [comment]
.dmg may give different different structure, it would be good to check

**Comment by sl4v3k** [comment]
looks like same thing, just one executable inside .dmg

**Comment by crbncl** [comment]
ah that makes sense.

damn, i guess just gotta keep analysing the file some more in order to crack it

**Comment by sl4v3k** [comment]
quickly checking, ther eis finction __APMInAppPurchaseItem_isFreeTrial, try patch this in order to return always false means 0, see how app will react

**Comment by crbncl** [comment]
Hmm, when I searched functions I didn’t come across anything named like that.

what decompiler are you using? It might be my program isn’t that great.

**Comment by sl4v3k** [comment]
```
__text:0000000100ACB784                         ; bool __cdecl -[APMInAppPurchaseItem isFreeTrial](APMInAppPurchaseItem *self, SEL)
__text:0000000100ACB784                         __APMInAppPurchaseItem_isFreeTrial_
__text:0000000100ACB784 00 20 40 39                             LDRB            W0, [X0,#8]
__text:0000000100ACB788 C0 03 5F D6                             RET
```
`just replace LDRB by XOR W0,W0`

**Comment by crbncl** [comment]
okay I patched that particular line and it didnt seem to have any effect once i loaded the app up.

i'll keep going through a bunch of different ones and test to see how they go!

**Comment by sl4v3k** [comment]
it was just guess, is this function called? try put garbage code and crash it if called.
