### ISSUE TITLE
5.603.xxxx version

### ISSUE THREAD

**Issue by Hamburjare** [sl4v3k/Shapr3d_crack#25]
Is there coming tool for 5.603.xxxx version in the near future?

**Comment by sl4v3k** [comment]
few days i guess

**Comment by sl4v3k** [comment]
are You from Shapr?

**Comment by Hamburjare** [comment]
nope

**Comment by sl4v3k** [comment]
because starting this version looks like They patch an issue

**Comment by yeye632** [comment]
hi，is there any progress on this new version, the code style is different, and didn't work after modify the bytes

**Comment by sl4v3k** [comment]
not yet, chust quickly checked but this version is patched already, will need some time to investigate new method

**Comment by sl4v3k** [comment]
check newest repo

**Comment by LasTCK** [comment]
Will new versions ever come?

**Comment by sl4v3k** [comment]
long time i wasnt checking whats new, hope so will come

**Comment by LasTCK** [comment]
> uzun zamandır yenilikleri kontrol etmiyordum, umarım gelir

Thanks to you, we were able to use the program, a new version would be nice. Only you shared the program. I didn't see anyone sharing it anywhere else.

**Comment by sl4v3k** [comment]
5.721.7564.0 #2f7b5dc3 is there

**Comment by LasTCK** [comment]
> 5.721.7564.0 #2f7b5dc3 orada

https://shapr3d.en.uptodown.com/windows/download/1029025388
;) burdan indirirler.

**Comment by LasTCK** [comment]
> 5.721.7564.0 #2f7b5dc3 orada

https://shapr3d.en.uptodown.com/windows
5.721.7564.0 
It's in this version but they didn't make it.

**Comment by sl4v3k** [comment]
what do You mean?

**Comment by LasTCK** [comment]
> 5.721.7564.0

I posted the link to the Shapr3D 5.721.7564.0 package installation program.
