### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by wahtsupp** [sl4v3k/Shapr3d_crack#9]
hello can help ?
whats the new   call    lic_call for the 5.493 
thanks sl4v3k

**Comment by wahtsupp** [comment]
[Shapr3D.zip](https://github.com/sl4v3k/Shapr3d_crack/files/13244090/Shapr3D.zip)

**Comment by sl4v3k** [comment]
check repo, just added

**Comment by jozko73** [comment]
I did that but it does not work for me. Can you please check what I did wrong. Thanks
Joe
[Shapr3D.zip](https://github.com/sl4v3k/Shapr3d_crack/files/13279690/Shapr3D.zip)

**Comment by sl4v3k** [comment]
there was mistake in an offset in the file, check update, should be 0x1B2E9C9 was 0x1B315C9

**Comment by jozko73** [comment]
Thanks.

**Comment by jozko73** [comment]
Sorry to bother you. It still doesn't work. Value E8 A2 D2 79 FF is pointing me to address 0x1B315C9.
It would be possible for you to post patched file?
Thanks
Joe

**Comment by sl4v3k** [comment]
so You have different version of shapr, just change bytes You found and must work

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by jozko73** [comment]
Version is same, but when installing for first time I had to log in to shapr account. If upgrading from previous version I didn't have to do that. So its working.
Thanks

**Comment by jozko73** [comment]
Anyway, they are already on version 5.550

**Comment by sl4v3k** [comment]
ok, will make an update
